# Use postgres/example user/password credentials
#localhost:5432/postgres-postgres-postgres
version: '3.5'

services:
  postgres:
    image: postgres
    container_name: "postgres"
    restart: always
    #    volumes:
    #      - ../../data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    expose: 
      - 5432
    hostname: postgres
#docker-compose -f postgres.yml up
